### ISSUE TITLE
Out of memory when building databases

### ISSUE THREAD

**Issue by n3ziniuka5** [pelias/interpolation#116] opened 2018-03-08 13:48 UTC
Hello,

I am trying to build `street.db` and `address.db`, but I am running out of RAM on the very first step. This is what I am running:
```
#!/bin/bash
set -euo pipefail

export BUILDDIR=...
export POLYLINE_FILE=.../planet.polylines

./script/import.sh
```

The process runs for a long time as ram usage is increasing and it eventually errors out. The machine has 236GB of RAM. The exact error was something about memalloc on array push, but I don't have the exact error message now as I've restarted the process and the error log is now empty. The process has now been running for ~7 hours now and is using 87GB of RAM, steadily increasing. I am sure it will run out of RAM again.

I am using the production branch.

The polylines files was created using
`pbf streets -f polyline planet-latest.osm.pbf > planet.polylines`

Any ideas what may be the issue here?

**Comment by orangejulius** [comment] 2018-03-08 17:35
Hey @n3ziniuka5,
This is interesting. In the past we've done full plant interpolation builds on machines with, if I recall correctly, under 32GB of RAM. It does take a while (many days) because it's the whole planet and not especially parallelized right now, but it should finish. @missinglink can chime in on suggestions for how to begin debugging

**Comment by n3ziniuka5** [comment] 2018-03-08 17:48
It would be great to have those databases already built and ready for download, especially if it takes many days to build them.

**Comment by orangejulius** [comment] 2018-03-08 20:31
You're in luck and we actually do have that already. We have not done a full build in many months because of the complexity, but here they are:
https://s3.us-east-2.amazonaws.com/pelias-data.nextzen.org/interpolation/07-13-2017-21%3A02%3A57/address.db.gz
https://s3.us-east-2.amazonaws.com/pelias-data.nextzen.org/interpolation/07-13-2017-21%3A02%3A57/street.db.gz

**Comment by n3ziniuka5** [comment] 2018-03-09 08:18
Thanks! Also, as I mentioned, I created the polylines file using the `pbf` tool. Do you know if using a recently created polylines file with a bit older `address.db`/`street.db` will impact accuracy or introduce some kind of inconsistency issues?

**Comment by orangejulius** [comment] 2018-03-09 13:16
It should be ok. It's better than intentionally using an older street dataset :)

**Comment by missinglink** [comment] 2018-03-25 08:12
Hi @n3ziniuka5, none of the scripts in this repo use significant amount of RAM so I'm a little confused what might be causing this.

We have had a number of reports of people trying to generate large polylines extracts using the `pbf streets` streets command I wrote.

I suspect that your error is with the polylines generation and not with the polylines import, is that correct?

**Comment by n3ziniuka5** [comment] 2018-10-17 08:32
Some time has passed and I am updating the data. This time I created the polylines file using `valhalla`. The resulting `planet.polylines` file is 2.6GB.

Now I am trying to create `address.db` and `street.db` files. I ran `./scripts/build.sh` and the script is struggling with the first step - importing polylines. Currently the process has already used up 17GB of ram and the usage is steadily increasing. It will probably keep increasing until it runs out of memory like the last time.

I could upload my `planet.polylines` somewhere if anyone would be willing to help me sort this out.

**Comment by n3ziniuka5** [comment] 2018-10-17 09:35
I have resolved the issue by applying this patch to the libpostal installation - https://github.com/openvenues/libpostal/issues/351#issuecomment-402778530

**Comment by missinglink** [comment] 2018-10-17 15:57
Good to hear @n3ziniuka5, if you're using our docker containers, I've patched them already in https://github.com/pelias/libpostal_baseimage/pull/1/files

Sorry it took so long, unfortunately, it turned out that the issue was within the `libpostal` binary which we don't control, it ended up taking a bunch of people reporting OOM errors before we figured out what was causing it and landed a patch.

I would love to get the patch merged in to `libpostal` but the author is unresponsive, so for now it requires devs to manually patch it against the bug :(

**Comment by missinglink** [comment] 2018-10-17 15:58
Closing this issue as a duplicate of https://github.com/pelias/interpolation/issues/132 which is now marked as resolved.

**Closed by missinglink** 2018-10-17 15:58 UTC

**Comment by monikgrover** [comment] 2019-04-16 11:51
> You're in luck and we actually do have that already. We have not done a full build in many months because of the complexity, but here they are:
> https://s3.us-east-2.amazonaws.com/pelias-data.nextzen.org/interpolation/07-13-2017-21%3A02%3A57/address.db.gz
> https://s3.us-east-2.amazonaws.com/pelias-data.nextzen.org/interpolation/07-13-2017-21%3A02%3A57/street.db.gz

Hi, these links are not working. Would you have new/latest links?
