### ISSUE TITLE
Prepare interpolation is very slow

### ISSUE THREAD

**Issue by msschl** [pelias/interpolation#242] opened 2020-03-12 11:04 UTC
I am building germany with your docker file but unfortunately the preparation step takes ages.

The container is currently running for 9 days with low resource consumption:
```
CONTAINER ID        NAME                                    CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
f4b85cf768fb        pelias_interpolation_run_53c4a0839ea5   16.66%              2.526GiB / 39.29GiB   6.43%               1.93MB / 0B         26.3GB / 0B         54
```

The tmp folder is about 1,1G
```
insgesamt 2,1G
-rw-r--r-- 1 kubernetes kubernetes 1,4G Mär 12 11:58 address.db
drwxr-xr-x 2 kubernetes kubernetes    6 Mär  2 22:43 builds
-rw-r--r-- 1 kubernetes kubernetes 129K Mär  4 05:39 conflate_oa.err
-rw-r--r-- 1 kubernetes kubernetes 1,5M Mär  4 05:39 conflate_oa.out
-rw-r--r-- 1 kubernetes kubernetes 127M Mär  4 05:39 conflate_oa.skip
-rw-r--r-- 1 kubernetes kubernetes 5,8M Mär 12 11:59 conflate_osm.err
-rw-r--r-- 1 kubernetes kubernetes 9,6M Mär 12 11:59 conflate_osm.out
-rw-r--r-- 1 kubernetes kubernetes   98 Mär  2 22:43 polyline.err
-rw-r--r-- 1 kubernetes kubernetes  35K Mär  2 23:24 polyline.out
-rw-r--r-- 1 kubernetes kubernetes 330M Mär  2 23:24 street.db
-rw-r--r-- 1 kubernetes kubernetes 154M Mär  2 23:24 street.db.gz
drwxr-xr-x 3 kubernetes kubernetes   21 Mär  4 05:39 tmp
```

The `conflating openstreetmap` step is running since the 3 March.

Is there any way to speed this process up?

**Comment by msschl** [comment] 2020-03-12 11:04
How long do your builds run?

**Comment by missinglink** [comment] 2020-03-12 18:43
Unfortunately it can be slow because of all the work it's doing but 9 days sounds extreme.

In theory it should be able to parallelize the work, I would suggest you try the following:

- generate the `street.db` once for all of Germany, don't bother rebuilding this again
- using the `street.db` create an `address.db` for Berlin with just `openstreetmap` and `openaddresses` data.
- repeat for other cities, see how long this takes (it should only take an hour per city)
- merge these `address.db` databases together, the primary IDs shouldn't matter, so you can discard them in the merge (this should take minutes)
- do the step which creates the vertices on the whole database once it's merged

The problem is it's been years since I wrote this code and I am not sure of the current state of it is, we have a scheduled job that runs and has done for years, we don't touch it!

I've been looking at the code again today and have begun making some performance improvements.

Since you're only importing Germany you can skip the `tiger` part completely.

Are you able to check that it hasn't stalled? Is it still consuming CPU and printing logs?

**Comment by msschl** [comment] 2020-03-12 19:25
It is definitely doing something. The CPU usage jumps sometimes up to 25%. 
My logs:
```
- importing polylines
- archiving street database
- conflating openaddresses
Mon Mar 2 22:24:52 UTC 2020 /data/openaddresses/de/hh/statewide.csv
Mon Mar 2 22:31:14 UTC 2020 /data/openaddresses/de/nw/city_of_cologne.csv
Mon Mar 2 22:38:17 UTC 2020 /data/openaddresses/de/nw/city_of_wesel.csv
Mon Mar 2 22:40:51 UTC 2020 /data/openaddresses/de/nw/city_of_wuppertal.csv
Mon Mar 2 22:43:23 UTC 2020 /data/openaddresses/de/nw/statewide.csv
Tue Mar 3 22:19:35 UTC 2020 /data/openaddresses/de/th/statewide.csv
- conflating openstreetmap
- conflating tiger
- interpolating vertices
```

It looks like it has finally finished the `conflating openstreetmap` step.

**Comment by missinglink** [comment] 2020-03-30 13:45
I spent a lot of time over the last two weeks improving the performance and stability of the interpolation builds in https://github.com/pelias/interpolation/pull/244

I was able to complete a full-planet build in ~4 days using that code, can you please retry with the latests code and open a new issue if need be.

**Closed by missinglink** 2020-03-30 13:45 UTC

**Comment by msschl** [comment] 2020-04-06 09:59
I was able to finish a full build in ~4 days as well. Thanks @missinglink for your work.

**Comment by kthye** [comment] 2023-01-10 16:14
Hi @missinglink, is this 4 day estimate for germany alone?

I've been trying to do a full build running import.sh for the last 7 days; it's still on the openaddresses conflation step, which from the logs have processed ~17 countries (currently on France, fr/countrywide.csv). Is there something I'm missing?
