### ISSUE TITLE
Error on download TIGER Data

### ISSUE THREAD

**Issue by cesclondon87** [pelias/interpolation#219] opened 2019-09-27 07:41 UTC
Hi Team,
During pelias download tiger, i noticed this error:
```
info: [interpolation(TIGER)] downloading all TIGER data
info: [interpolation(TIGER)] Downloaded tl_2016_01001_addrfeat.zip
error: [interpolation(TIGER)]  message=426 Failure writing network stream., stack=Error: 426 Failure writing network stream.
    at Ftp.parse (/code/pelias/interpolation/node_modules/jsftp/lib/jsftp.js:223:11)
    at Ftp.parseResponse (/code/pelias/interpolation/node_modules/jsftp/lib/jsftp.js:146:8)
    at Stream.pipeline.on.data (/code/pelias/interpolation/node_modules/jsftp/lib/jsftp.js:112:10)
    at Stream.emit (events.js:198:13)
    at ResponseParser.reemit (/code/pelias/interpolation/node_modules/duplexer/index.js:70:25)
    at ResponseParser.emit (events.js:198:13)
    at readableAddChunk (/code/pelias/interpolation/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at ResponseParser.Readable.push (/code/pelias/interpolation/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at ResponseParser.Transform.push (/code/pelias/interpolation/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at ResponseParser.<anonymous> (/code/pelias/interpolation/node_modules/ftp-response-parser/index.js:62:12), code=426

```
How can I resolve it? I tried to download manually here => https://census-backup.s3.amazonaws.com/tiger/2016/ADDRFEAT/index.html but it doesn't works.

**Comment by missinglink** [comment] 2019-09-27 09:24
dupe of https://github.com/pelias/docker/issues/135

**Closed** 2019-09-27 09:25 UTC
